/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Ender
 * Created: Oct 13, 2017
 */
CREATE TABLE CERTIFICATES (ID_CERT INTEGER PRIMARY KEY, CN VARCHAR(200), ID_ISSUER_CERT INTEGER);
CREATE TABLE PRIVATE_KEYS (ID_CERT INTEGER PRIMARY KEY,	CN VARCHAR(200), ID_ISSUER_CERT INTEGER);
CREATE TABLE PGP_PRIVATE_KEYS (ID_CERT INTEGER PRIMARY KEY, KEYNAME VARCHAR(64), ID_PARENT_KEY INTEGER);
CREATE TABLE PGP_PUBLIC_KEYS (ID_KEY INTEGER PRIMARY KEY, KEYNAME VARCHAR(64), ID_PARENT_KEY INTEGER);

/* ALGO */
CREATE TABLE ALGO (ID_ALGO INTEGER PRIMARY KEY, ALGONAME VARCHAR(64), TYPE VARCHAR(64));
/* SIGNATURE ALGORITHMS from DefaultSignatureAlgorithmIdentifierFinder class */
INSERT INTO ALGO VALUES (1, 'MD2WITHRSAENCRYPTION','SIGNATURE');
INSERT INTO ALGO VALUES (2, 'MD2WITHRSA','SIGNATURE');
INSERT INTO ALGO VALUES (3, 'MD5WITHRSA','SIGNATURE');
INSERT INTO ALGO VALUES (4, 'SHA1WITHRSA ','SIGNATURE');
INSERT INTO ALGO VALUES (5, 'SHA224WITHRSA ','SIGNATURE');
INSERT INTO ALGO VALUES (6, 'SHA256withRSA','SIGNATURE');
INSERT INTO ALGO VALUES (7, 'SHA384withRSA','SIGNATURE');
INSERT INTO ALGO VALUES (8, 'SHA512withRSA','SIGNATURE');
INSERT INTO ALGO VALUES (9, 'SHA1WITHRSAANDMGF1','SIGNATURE');
INSERT INTO ALGO VALUES (10, 'SHA224WITHRSAANDMGF1','SIGNATURE');
INSERT INTO ALGO VALUES (11, 'SHA256WITHRSAANDMGF1','SIGNATURE');
INSERT INTO ALGO VALUES (12, 'SHA384WITHRSAANDMGF1','SIGNATURE');
INSERT INTO ALGO VALUES (13, 'SHA512WITHRSAANDMGF1','SIGNATURE');
INSERT INTO ALGO VALUES (14, 'RIPEMD160WITHRSA','SIGNATURE');
INSERT INTO ALGO VALUES (15, 'RIPEMD128WITHRSA','SIGNATURE');
INSERT INTO ALGO VALUES (16, 'RIPEMD256WITHRSA','SIGNATURE');
INSERT INTO ALGO VALUES (17, 'SHA1WITHDSA','SIGNATURE');
INSERT INTO ALGO VALUES (18, 'DSAWITHSHA1','SIGNATURE');
INSERT INTO ALGO VALUES (19, 'SHA224WITHDSA','SIGNATURE');
INSERT INTO ALGO VALUES (20, 'SHA256WITHDSA','SIGNATURE');
INSERT INTO ALGO VALUES (21, 'SHA384WITHDSA','SIGNATURE');
INSERT INTO ALGO VALUES (22, 'SHA512WITHDSA','SIGNATURE');
INSERT INTO ALGO VALUES (23, 'SHA1WITHECDSA','SIGNATURE');
INSERT INTO ALGO VALUES (24, 'ECDSAWITHSHA1','SIGNATURE');
INSERT INTO ALGO VALUES (25, 'SHA224WITHECDSA','SIGNATURE');
INSERT INTO ALGO VALUES (26, 'SHA256WITHECDSA','SIGNATURE');
INSERT INTO ALGO VALUES (27, 'SHA384WITHECDSA','SIGNATURE');
INSERT INTO ALGO VALUES (28, 'SHA512WITHECDSA','SIGNATURE');
INSERT INTO ALGO VALUES (29, 'GOST3411WITHGOST3410','SIGNATURE');
INSERT INTO ALGO VALUES (30, 'GOST3411WITHGOST3410-94','SIGNATURE');
INSERT INTO ALGO VALUES (31, 'GOST3411WITHECGOST3410','SIGNATURE');
INSERT INTO ALGO VALUES (32, 'GOST3411WITHECGOST3410-2001','SIGNATURE');
INSERT INTO ALGO VALUES (33, 'GOST3411WITHGOST3410-2001','SIGNATURE');
/* PRIVATE KEY ALGORITHMS from RSA DSA DH (DiffieHellman) */
INSERT INTO ALGO VALUES (34, 'RSA','PKCS8');
INSERT INTO ALGO VALUES (35, 'DSA','PKCS8');
INSERT INTO ALGO VALUES (36, 'DH','PKCS8');