/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Ender
 * Created: Oct 13, 2017
 */
CREATE TABLE CERTIFICATES (ID_CERT INTEGER PRIMARY KEY, CN VARCHAR(200), ID_ISSUER_CERT INTEGER);
CREATE TABLE PRIVATE_KEYS (ID_CERT INTEGER PRIMARY KEY,	CN VARCHAR(200), ID_ISSUER_CERT INTEGER);
CREATE TABLE PGP_PRIVATE_KEYS (ID_CERT INTEGER PRIMARY KEY, KEYNAME VARCHAR(64), ID_PARENT_KEY INTEGER);
CREATE TABLE PGP_PUBLIC_KEYS (ID_KEY INTEGER PRIMARY KEY, KEYNAME VARCHAR(64), ID_PARENT_KEY INTEGER);